name: Testing
on:
  workflow_dispatch:
  push:

jobs:
  determine-team:
    runs-on: ubuntu-latest

    outputs:
      team: ${{ steps.choose_team.outputs.team }}

    steps:
      - name: Choose team from variable
        id: choose_team
        shell: python
        env:
          TEST_VALUES: ${{ vars.TEST }}
        run: |
          import os

          test = os.environ['TEST_VALUES']

          print(test)

          test = test.split(',')

          test.append('10000')
          
          test = ','.join(test)

          print(test)

          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f'test={test}\n', file=fh)

      - uses: actions/checkout@v3
      - name: Update team value
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_UPDATE_VARIABLES }}
        run: gh variable set TEST --body ${{ steps.choose_team.outputs.test }}
