name: Test setting repo variables
on:
  workflow_dispatch

jobs:
  update-variable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh variable set TEST_VAR --body "TOR"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_UPDATE_VARIABLES }}
