name: Tweet Rotating Pitcher WAR Swarm Plot
on:
  schedule:
    - cron: 20 15-23 * * *

  workflow_dispatch:
    

jobs:
  determine-team:
    runs-on: ubuntu-latest

    outputs:
      team: ${{ steps.choose_team.outputs.team }}

    steps:
      - name: Choose team from variable
        id: choose_team
        shell: python
        env:
          MLB_TEAM_VALUE_B: ${{ vars.MLB_TEAM_VALUE_B }}
        run: |
          import os

          team_value = int(os.environ['MLB_TEAM_VALUE_B'])

          if team_value > 29:
            team_value = 0

          teams = ["ARI", "ATH", "ATL", "BAL", "BOS", "CHC", "CHW", "CIN", "CLE", "COL", "DET",
                   "HOU", "KCR", "LAA", "LAD", "MIA", "MIL", "MIN", "NYM", "NYY", "PHI", "PIT",
                   "SDP", "SEA", "SFG", "STL", "TBR", "TEX", "TOR", "WSN"]

          team = teams[team_value]

          team_value += 1

          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f'team={team}\n', file=fh)
              print(f'team_value={team_value}', file=fh)

      - uses: actions/checkout@v3
      - name: Update team value
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_UPDATE_VARIABLES }}
        run: gh variable set MLB_TEAM_VALUE_B --body ${{ steps.choose_team.outputs.team_value }}
                   
  gather-plot:
    needs: determine-team
    uses: hockey-stats/chart-plotting/.github/workflows/plot_pitcher_war.yml@main
    with:
      team: ${{ needs.determine-team.outputs.team }}
      minimum_ips: 10

  tweet-plot:
    runs-on: ubuntu-latest
    needs: [gather-plot, determine-team]
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      BSKY_LOGIN: ${{ secrets.BSKY_LOGIN }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}

      TEAM: ${{ needs.determine-team.outputs.team }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download Charts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
       
      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Get Team Details
        id: team_details
        run: python3 get_mlb_team_details.py $TEAM
      
      - name: Send Skeet
        run: |
          python3 skeet_picture.py -i ${TEAM}_wrc.png -t "${{ steps.team_details.outputs.team_full_name }} pitchers by WAR ${{ steps.team_details.outputs.hashtag }} #MLB";

   #   - name: Send Tweet
   #     run: |
   #       python3 tweet_picture.py -i ${TEAM}_skater_g_ratios.png -t "${{ steps.team_details.outputs.team_full_name }} hitters by wRC+`` ${{ steps.team_details.outputs.hashtag }} #NHL";

