name: Tweet Rotating Run Differential Rolling Average Plot
on:
  schedule:
    - cron: 0 18 */2 * *

  workflow_dispatch:
    

jobs:
  determine-div:
    runs-on: ubuntu-latest

    outputs:
      div_value: ${{ steps.choose_div.outputs.div_value }}

    steps:
      - name: Choose team from variable
        id: choose_div
        shell: python
        env:
          MLB_DIV_VALUE: ${{ vars.MLB_DIV_VALUE }}
        run: |
          import os

          div_value = int(os.environ['MLB_DIV_VALUE'])

          if div_value >= 5:
            div_value = 0

          div_value += 1

          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f'div_value={div_value}', file=fh)

      - uses: actions/checkout@v3
      - name: Update division value
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_UPDATE_VARIABLES }}
        run: gh variable set MLB_DIV_VALUE --body ${{ steps.choose_div.outputs.div_value }}
                   
  gather-plot:
    needs: determine-div
    uses: hockey-stats/chart-plotting/.github/workflows/plot_rolling_run_diff.yml@main
    with:
      division: ${{ needs.determine-div.outputs.div-value }}
    permissions:
      actions: write
      contents: read

  tweet-plot:
    runs-on: ubuntu-latest
    needs: [gather-plot, determine-div]
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      BSKY_LOGIN: ${{ secrets.BSKY_LOGIN }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download Charts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
       
      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Get Team Details
        id: team_details
        run: python3 get_mlb_team_details.py $TEAM
      
      - name: Send Skeet
        run: |
          python3 skeet_picture.py -i run_diff_rolling_avg.png -t "Run differential 10-game rolling average for ${{ needs.determine-div.outputs.division }} teams #MLB";

   #   - name: Send Tweet
   #     run: |
   #       python3 tweet_picture.py -i ${TEAM}_skater_g_ratios.png -t "${{ steps.team_details.outputs.team_full_name }} hitters by wRC+`` ${{ steps.team_details.outputs.hashtag }} #NHL";

