name: Tweet All Skaters xG Ratios Plot
on:
  schedule:
    - cron: 30 15 * * */4

  workflow_dispatch:
    
jobs:
  gather-plot:
    uses: hockey-stats/chart-plotting/.github/workflows/scrape_and_plot_skater_tables.yml@main
    with:
      team: 'ALL'
      minimum_icetime: 100
    secrets: inherit

  tweet-plot:
    runs-on: ubuntu-latest
    needs: gather-plot
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      BSKY_LOGIN: ${{ secrets.BSKY_LOGIN }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
    ###
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #
      - name: Download Charts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}
      #
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      # 
      - name: Install Requirements
        run: pip install -r requirements.txt
      #
      - name: Send Skeet
        run: |
          python3 skeet_picture.py -i ALL_skater_xg_ratios.png -t "5v5 on-ice xG results for all skaters #NHL";
      #
      - name: Send Tweet
        run: |
          python3 tweet_picture.py -i ALL_skater_xg_ratios.png -t "5v5 on-ice xG results for all skaters #NHL";
    ###
