name: Tweet Game Report
on:
  workflow_dispatch:
    
  schedule:
    - cron: '*/15 2-6 * * *'


jobs:
  get-last-game-id:
    runs-on: ubuntu-latest
  
    outputs:
      last_game_id: ${{ steps.get_id.outputs.last_game_id}}

    steps:
      - name: Get last game id
        id: get_id
        env:
          LAST_GAME_ID: ${{ vars.LAST_GAME_REPORT_ID }}
        run: echo "last_game_ID=$LAST_GAME_ID" >> "$GITHUB_OUTPUT"


  gather-plot:
    permissions:
      actions: write
      contents: read

    needs: get-last-game-id

    uses: hockey-stats/chart-plotting/.github/workflows/scrape_and_plot_game_reports.yml@main
    with:
      last_game_id: ${{ needs.get-last-game-id.outputs.last_game_id }}

  tweet-plot:
    runs-on: ubuntu-latest
    needs: gather-plot

    if: needs.gather-plot.outputs.game_id != 'NONE'

    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      BSKY_LOGIN: ${{ secrets.BSKY_LOGIN }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download charts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Get Game Details
        id: game_details
        env:
          PYTHONPATH: ${ github.workspace }
        run: |
          FILENAME=$(ls game-plot/*png);
          python3 get_game_details.py $FILENAME

      - name: Send Tweet
        run: |
          python3 tweet_picture.py -i ${{ steps.game_details.outputs.image_filename }} -t "${{ steps.game_details.outputs.tweet_body }}"

      - name: Send Skeet
        run: |
          python3 skeet_picture.py -i ${{ steps.game_details.outputs.image_filename }} -t "${{ steps.game_details.outputs.tweet_body }}"

      - name: Update last game ID org variable
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_UPDATE_VARIABLES }}
          GAME_ID: ${{ needs.gather-plot.outputs.game_id }}
        run: gh variable set LAST_GAME_REPORT_ID --body $GAME_ID