name: Tweet All Team 5on4 Offense Chart
on:
  schedule:
    - cron: 0 17 * * */4

  workflow_dispatch:
    
jobs:
  gather-plot:
    uses: hockey-stats/chart-plotting/.github/workflows/scrape_and_plot_special_teams_tables.yml@main
    with:
      situation: '5on4'

  tweet-plot:
    runs-on: ubuntu-latest
    needs: gather-plot
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      BSKY_LOGIN: ${{ secrets.BSKY_LOGIN }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
    ###
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #
      - name: Download Charts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}
      #
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      # 
      - name: Install Requirements
        run: pip install -r requirements.txt
      #
      - name: Send Tweet
        run: |
          python3 tweet_picture.py -i special-teams-plots/5on4_offence.png -t "5on4 Power Play offence for all teams. #NHL";
      #
      - name: Send Skeet
        run: |
          python3 skeet_picture.py -i special-teams-plots/5on4_offence.png -t "5on4 Power Play offence for all teams. #NHL";
    ###
