name: Tweet Single-Team Skater xG Ratios Plot
on:
  schedule:
    #- cron: 0 15 * * */2
    - cron: 22 * * * * 

  workflow_dispatch:
    inputs:
      team:
        type: string
        default: "TOR"
        description: "Team for which to generate plots"

      icetime:
        type: number
        default: 50
        description: "Minimum icetime to use for cutoff"
    
jobs:
  ############
  ## Manual ##
  ############
  gather-plot-manual:
    if: github.event_name == 'workflow_dispatch'
    uses: hockey-stats/chart-plotting/.github/workflows/scrape_and_plot_skater_tables.yml@main
    with:
      team: ${{ inputs.team }}
      minimum_icetime: 50
  
  tweet-plot-manual:
    runs-on: ubuntu-latest
    needs: gather-plot-manual
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Charts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
       
      - name: Install Requirements
        run: pip install -r requirements.txt
      
      - name: Send Tweet
        env:
          TEAM: ${{ inputs.team }}
        run: |
          ls; 
          python3 tweet_picture.py -i skater-plots/${TEAM}_skater_xg_ratios.png -t "${TEAM} 5v5 on-ice xG results";

  #################
  ### Scheduled ###
  #################
  gather-plot-schedule:
    if: github.event_name == 'schedule'
    uses: hockey-stats/chart-plotting/.github/workflows/scrape_and_plot_skater_tables.yml@main
    with:
      team: "TOR"
      minimum_icetime: 50

  tweet-plot-schedule:
    runs-on: ubuntu-latest
    needs: gather-plot-schedule
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download Charts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
       
      - name: Install Requirements
        run: pip install -r requirements.txt
      
      - name: Send Tweet
        run: |
          python3 tweet_picture.py -i skater-plots/TOR_skater_xg_ratios.png -t "Toronto 5v5 on-ice xG results #LeafsForever";
