name: Tweet Game Report
on:
  workflow_dispatch:
    
  schedule:
    - cron: '*/15 2-6 * * *'

jobs:
  gather-plot:
    uses: hockey-stats/chart-plotting/.github/workflows/scrape_and_plot_game_reports.yml@main

  tweet-plot:
    runs-on: ubuntu-latest
    needs: gather-plot

    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download charts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Get Game Details
        id: game_details
        env:
          PYTHONPATH: ${ github.workspace }
        run: |
          FILENAME=$(ls *png)
          python3 get_game_details.py $FILENAME

      - name: Send Tweet
        run: |
          python3 tweet_picture.py -i ${{ steps.team_details.outputs.image_filename }} -t "${{ steps.team_details.outputs.tweet_body }}""