name: Tweet All Skaters xG Ratios Plot
on:
  push:
  schedule:
    - cron: 30 17 * * 4

  workflow_dispatch:
    
jobs:
  gather-plot:
    uses: hockey-stats/chart-plotting/.github/workflows/scrape_and_plot_special_teams_tables.yml@main
    with:
      situation: '4on5'

  tweet-plot:
    runs-on: ubuntu-latest
    needs: gather-plot
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    ###
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #
      - name: Download Charts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}
      #
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      # 
      - name: Install Requirements
        run: pip install -r requirements.txt
      #
      - name: Send Tweet
        run: |
          python3 tweet_picture.py -i 5on4_offence.png -t "4on5 Penalty Kill defense for all teams. #NHL";
    ###
