name: Tweet Team Run Differential Scatter Plot
on:
  schedule:
    - cron: 0 16 * * */3

  workflow_dispatch:
    

jobs:
  gather-plot:
    uses: hockey-stats/chart-plotting/.github/workflows/plot_run_diff_scatter.yml@main

  tweet-plot:
    runs-on: ubuntu-latest
    needs: gather-plot
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      BSKY_LOGIN: ${{ secrets.BSKY_LOGIN }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download Charts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.gather-plot.outputs.plot_artifact_name }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
       
      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Send Skeet
        run: |
          python3 skeet_picture.py -i team_run_diff.png -t "Runs scored vs runs allowed for all MLB teams #MLB";

   #   - name: Send Tweet
   #     run: |
   #       python3 tweet_picture.py -i ${TEAM}_skater_g_ratios.png -t "${{ steps.team_details.outputs.team_full_name }} hitters by wRC+`` ${{ steps.team_details.outputs.hashtag }} #NHL";

